from .UFExtrator import apiParaSql_UF_SQLAlchemy
from .UFExtrator import atualizarEstatisticasUFs
from .MesorregiaoExtrator import apiParaSql_Mesorregiao_SQLAlchemy
from .MicrorregiaoExtrator import apiParaSql_Microrregiao_SQLAlchemy
from .MunicipioExtrator import apiParaSql_Municipio_SQLAlchemy
from .MunicipioExtrator import atualizarEstatisticasMunicipios
from .RegiaoExtrator import apiParaSql_Regiao_SQLAlchemy
