"""initial migration

Revision ID: 90d9591135dd
Revises: 
Create Date: 2025-09-01 21:27:40.825902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d9591135dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_cartorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('cnpj', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_cartorio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_cartorio_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_tb_cartorio_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_cartorio_nome'), ['nome'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_cartorio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_cartorio_nome'))
        batch_op.drop_index(batch_op.f('ix_tb_cartorio_email'))
        batch_op.drop_index(batch_op.f('ix_tb_cartorio_cnpj'))

    op.drop_table('tb_cartorio')
    # ### end Alembic commands ###
