"""Criacao das tabelas

Revision ID: cfbd5790abc8
Revises: 
Create Date: 2025-08-18 21:08:45.049848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfbd5790abc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_regiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('total_morte', sa.Integer(), nullable=True),
    sa.Column('total_nascimento', sa.Integer(), nullable=True),
    sa.Column('total_casamento', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('regiao_id', sa.Integer(), nullable=False),
    sa.Column('total_morte', sa.Integer(), nullable=True),
    sa.Column('total_nascimento', sa.Integer(), nullable=True),
    sa.Column('total_casamento', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regiao_id'], ['tb_regiao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_mesorregiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('uf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uf_id'], ['tb_uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_microrregiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('mesorregiao_id', sa.Integer(), nullable=False),
    sa.Column('uf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mesorregiao_id'], ['tb_mesorregiao.id'], ),
    sa.ForeignKeyConstraint(['uf_id'], ['tb_uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('uf_id', sa.Integer(), nullable=False),
    sa.Column('microrregiao_id', sa.Integer(), nullable=False),
    sa.Column('total_morte', sa.Integer(), nullable=True),
    sa.Column('total_nascimento', sa.Integer(), nullable=True),
    sa.Column('total_casamento', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['microrregiao_id'], ['tb_microrregiao.id'], ),
    sa.ForeignKeyConstraint(['uf_id'], ['tb_uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_municipio')
    op.drop_table('tb_microrregiao')
    op.drop_table('tb_mesorregiao')
    op.drop_table('tb_uf')
    op.drop_table('tb_regiao')
    # ### end Alembic commands ###
