"""Criando as tabelas

Revision ID: ef85460ef81b
Revises: 
Create Date: 2025-08-19 10:49:50.669037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef85460ef81b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_regiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_regiao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_regiao_sigla'), ['sigla'], unique=False)

    op.create_table('tb_uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cod_regiao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_regiao'], ['tb_regiao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_uf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_uf_cod_regiao'), ['cod_regiao'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_uf_sigla'), ['sigla'], unique=False)

    op.create_table('tb_mesorregiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cod_uf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_uf'], ['tb_uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_mesorregiao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_mesorregiao_cod_uf'), ['cod_uf'], unique=False)

    op.create_table('tb_uf_estatistica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_uf', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('total_nascimento', sa.Integer(), nullable=True),
    sa.Column('total_morte', sa.Integer(), nullable=True),
    sa.Column('total_casamento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cod_uf'], ['tb_uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_uf_estatistica', schema=None) as batch_op:
        batch_op.create_index('idx_uf_ano', ['cod_uf', 'ano'], unique=True)
        batch_op.create_index(batch_op.f('ix_tb_uf_estatistica_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_uf_estatistica_cod_uf'), ['cod_uf'], unique=False)

    op.create_table('tb_microrregiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cod_mesorregiao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_mesorregiao'], ['tb_mesorregiao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_microrregiao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_microrregiao_cod_mesorregiao'), ['cod_mesorregiao'], unique=False)

    op.create_table('tb_municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cod_uf', sa.Integer(), nullable=False),
    sa.Column('cod_microrregiao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_microrregiao'], ['tb_microrregiao.id'], ),
    sa.ForeignKeyConstraint(['cod_uf'], ['tb_uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_municipio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_municipio_cod_microrregiao'), ['cod_microrregiao'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_municipio_cod_uf'), ['cod_uf'], unique=False)

    op.create_table('tb_municipio_estatistica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_municipio', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('total_nascimento', sa.Integer(), nullable=True),
    sa.Column('total_morte', sa.Integer(), nullable=True),
    sa.Column('total_casamento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cod_municipio'], ['tb_municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_municipio_estatistica', schema=None) as batch_op:
        batch_op.create_index('idx_municipio_ano', ['cod_municipio', 'ano'], unique=True)
        batch_op.create_index(batch_op.f('ix_tb_municipio_estatistica_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_municipio_estatistica_cod_municipio'), ['cod_municipio'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_municipio_estatistica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_municipio_estatistica_cod_municipio'))
        batch_op.drop_index(batch_op.f('ix_tb_municipio_estatistica_ano'))
        batch_op.drop_index('idx_municipio_ano')

    op.drop_table('tb_municipio_estatistica')
    with op.batch_alter_table('tb_municipio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_municipio_cod_uf'))
        batch_op.drop_index(batch_op.f('ix_tb_municipio_cod_microrregiao'))

    op.drop_table('tb_municipio')
    with op.batch_alter_table('tb_microrregiao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_microrregiao_cod_mesorregiao'))

    op.drop_table('tb_microrregiao')
    with op.batch_alter_table('tb_uf_estatistica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_uf_estatistica_cod_uf'))
        batch_op.drop_index(batch_op.f('ix_tb_uf_estatistica_ano'))
        batch_op.drop_index('idx_uf_ano')

    op.drop_table('tb_uf_estatistica')
    with op.batch_alter_table('tb_mesorregiao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_mesorregiao_cod_uf'))

    op.drop_table('tb_mesorregiao')
    with op.batch_alter_table('tb_uf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_uf_sigla'))
        batch_op.drop_index(batch_op.f('ix_tb_uf_cod_regiao'))

    op.drop_table('tb_uf')
    with op.batch_alter_table('tb_regiao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_regiao_sigla'))

    op.drop_table('tb_regiao')
    # ### end Alembic commands ###
